### ISSUE TITLE
db migrate error

### ISSUE THREAD

**Issue by vladimirk85** [instructure/canvas-lms#1054]
### Summary:
Hi. I am trying to install analytics plugin using this instruction https://github.com/instructure/analytics while running "sudo rake db:migrate RAILS_ENV=development" I am getting an error below.

### error:

```
sudo rake db:migrate RAILS_ENV=development
[sudo] password for asys: 
/usr/local/lib/ruby/gems/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/soap4r-ruby1.9-2.0.0/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/redis-3.3.1/lib/redis/client.rb:459: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/redis-3.3.1/lib/redis/client.rb:459: warning: constant ::Fixnum is deprecated
1: development:public
rake aborted!
NoMethodError: undefined method `db' for nil:NilClass
/home/asys/canvas-lms/db/migrate/20140224212705_remove_cassandra_page_views_contributed.rb:13:in `runnable?'
/home/asys/canvas-lms/config/initializers/active_record.rb:1178:in `runnable?'
/home/asys/canvas-lms/config/initializers/active_record.rb:1212:in `select'
/home/asys/canvas-lms/config/initializers/active_record.rb:1212:in `runnable'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

also the cassandra.yml file have following configs:

### cassandra.yml:

```
 development:
   page_views:
     servers:
     - 127.0.0.1:9160
     keyspace: page_views
   auditors:
     servers:
     - 127.0.0.1:9160
     keyspace: auditors
# test:
#   page_views:
#     servers:
#     - 127.0.0.1:9160
#     keyspace: page_views_test
#   auditors:
#     servers:
#     - 127.0.0.1:9160
#     keyspace: auditors_test
```

can you help me to solve this issue?
