### ISSUE TITLE
Mastery path not display in selfhost

### ISSUE THREAD

**Issue by GTMtremolo** [instructure/canvas-lms#1694]
**Summary: Trying to use the Mastery Path but it is not displaying. We also do not have the conditional release API Admin apparently when it was installed.**
Steps to reproduce:

1. Create Course
2. Activate Mastery Plugin
3. Create Module

Create Assignment and Indented assignment
Expected behavior:
**I expect the Mastery Path to be present on the options.**

Actual behavior:
**Mastery Path is not present.**

**Comment by alissonash** [comment]
I have the same problem.

It looks like you need to configure the file: config/conditional_release.yml.example

```
development:
  # required to enable the feature. default is false.
  enabled: false

  # required. host of the url to the conditional release service. no default.
  host: conditional_release.docker

  # optional. default matches Canvas
  protocol: https

```
But so far, I haven't been able to find any documents about it. I still don't know where to get the values ​​for this .yml
