### ISSUE TITLE
Ran docker_dev_setup without installing Dory, no errors, but can't reach Canvas app via browser

### ISSUE THREAD

**Issue by mchavarriagam** [instructure/canvas-lms#2036]
### Summary:

Ran docker_dev_setup.sh without installing Dory (as it seemed optional), install went through fine without errors, then ran "sudo docker-compose up -d" also without errors, but I'm not sure how to reach Canvas app on browser.
### Steps to reproduce:

 1. Git clone then run docker_dev_setup.sh without installing Dory.
 2. Install notes mention http://canvas.docker 
 3. Run docker-compose up -d
 4. Go to http://canvas.docker

### Expected behavior:

Something should load

### Actual behavior:

"This site can’t be reached" error.

### Additional notes:

1. Running Ubuntu 20.04 with a fresh Docker install and Docker Compose 1.27.4
2. Did not install Dory. According to documentation it's optional.
3. Also tried localhost, localhost:3000, 127.0.1.1. etc.
4. Absolutely new to Docker so I'm not sure what I should be looking for or where to check logs or in general what to do.
5. docker-compose.override.yml contains the following:
````
web:
    <<: *BASE
    environment:
      <<: *BASE-ENV
      VIRTUAL_HOST: .canvas.docker
      HTTPS_METHOD: noredirect
      # AR_QUERY_TRACE: 'true'
      # AR_QUERY_TRACE_TYPE: 'all' # 'all', 'write', or 'read'
      # AR_QUERY_TRACE_LINES: 10
````
