### ISSUE TITLE
Outbound email notifications aren't working

### ISSUE THREAD

**Issue by eharvey71** [instructure/canvas-lms#2265]
### Bitnami Canvas image - Sending email notifications isn't working
I'm currently using the AWS Bitnami image (Ubuntu 20.04) for deploying Canvas and they are referring folks back to canvas-lms for help. I'm having a good experience with this so far (fixed issues with SSL, LTI, SIS Imports, and RCE API), but emails are still not sending.

I'm using Brevo for my SMTP relay and everything is good when testing against that account from the server command line:
```
curl --ssl --url 'smtps://smtp-relay.sendinblue.com:465' --mail-from mytestdomain@gmailaddr.com / 
--mail-rcpt myemail@gmailaddr.com --upload-file email.txt --user '{brevo-user}:{brevo-password}'
```
... so I know I've got a clear path to the SMTP server.

### Steps to reproduce:
1 ) Change the outgoing_mail.yml to the desired config and restart services:

```
production:
  address: "smtp-relay.sendinblue.com"
  port: "465"
  enable_starttls_auto: false
  ssl: true
  user_name: "{brevo-user}"
  password: "{brevo-password}"
  authentication: "login" # plain, login, or cram_md5
  domain: "sendinblue.com"
  outgoing_address: "{my outgoing email}"
  default_name: "Instructure Canvas"
```

2) I've tried authentication using plain, login, and cram_md5 and I'm ASSUMING it should be login.
3) I also do not understand what is expected in domain. There's no good explanation [in your docs ](https://github.com/instructure/canvas-lms/wiki/Production-Start#outgoing-mail-configuration)other than "Canvas needs it".
4) I've tried all methods of setting ssl to true and false, as well as enable_starttls_auto - both true and false.
5) I'm able to observe the email attempt in the /log/delayed_job.log
6) The admin-level feature flags for all accounts are set to "Allow the ability to send notifications through our dispatch queue".
7) Followed Bitnami initially but didn't work: https://docs.bitnami.com/aws/apps/canvaslms/configuration/configure-smtp/
8) Attempted Bitnami's troubleshooting for SMTP: https://docs.bitnami.com/general/how-to/troubleshoot-smtp-issues/

### Expected behavior:
Notification emails to be sent from Canvas LMS.

### Actual behavior:
All actions happen and nothing is sent.
