### ISSUE TITLE
Fix visual bug on grade

### ISSUE THREAD

**Issue by lishaduck** [instructure/canvas-lms#2500]
I whipped out inspect to figure out this peeve of mine lol

Some grades have this:

<img width="63" alt="Image" src="https://github.com/user-attachments/assets/24e4d92e-881b-46cf-aea8-1aa99e68b39c" />

Add this:

```css
/** Licensed CC0 */
#grades_summary td.details a {
  text-decoration: none;
}
```

To this section:
https://github.com/instructure/canvas-lms/blob/7b48e8255fc392dce27d4fbb12488bb5d2666056/app/stylesheets/bundles/grade_summary.scss#L172-L179

Now it looks like this:

<img width="63" alt="Image" src="https://github.com/user-attachments/assets/c1188960-850b-47f8-bf46-3742751bc02a" />
