### ISSUE TITLE
Canvas LMS High Memory Usage Causing EC2 Instance Freeze

### ISSUE THREAD

**Issue by MijanurR** [instructure/canvas-lms#2513]
I have set up a production-ready Canvas LMS application on my EC2 instance, which is configured with 8 GB of RAM and 80 GB of storage.

During initial usage with just 4 users, the application became unresponsive after a short period. Upon inspecting the EC2 instance, we found that it had consumed the entire 8 GB of RAM. After restarting the apache2 service, we noticed that a deployed job was using a large amount of memory and not releasing it even after completion.

My concern is that the application becomes non-functional with as few as 4 users. Is there a known solution for this behavior, or are there any configuration changes or optimizations that should be applied to prevent this?

**Comment by nosadcoder** [comment]
On config/delayed_jobs.yml,  set some arguments for delayed jobs.  look like this
```
production:
  workers:
  - queue: canvas_queue
    workers: 1
    max_priority: 10
  - queue: canvas_queue
    workers: 1
```
And,  run command ``` RAILS_ENV=production ./script/delayed_job restart``` to restart delayed jobs.
