### ISSUE TITLE
[BUG] Star icon is the same for favorite and non favorite courses

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#595]
Hi everyone, 

It's been a while :)
I updated my application to the very latest "stable" version and I have a new issue on this page: 
https://my.domain.com/courses

The page where you can select favorite courses. The star icon remains black whatever the favorite status is. 

I've made a quick fix in my "global.css" file: 

```css
/* Quick fix for favorite course icon */
span.course-list-favoritable i.icon-star{
        color: lightgray;
}

span.course-list-favoritable.course-list-favorite-course i.icon-star{
        color: black;
}
```

If I am the only one having this issue it may means that I had a problem with the merge at some point. If not, then this is definitely an issue :)

Thanks you all, 
Regis.
